// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package data

import (
	"database/sql"
	"time"
)

type Note struct {
	ID        int32          `json:"id"`
	Title     string         `json:"title"`
	Content   sql.NullString `json:"content"`
	CreatedAt time.Time      `json:"created_at"`
}
