// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: update_note.sql

package data

import (
	"context"
	"database/sql"
)

const updateNote = `-- name: UpdateNote :one
UPDATE notes
SET title = $2,
    content = $3
WHERE id = $1
RETURNING id, title, content, created_at
`

type UpdateNoteParams struct {
	ID      int32          `json:"id"`
	Title   string         `json:"title"`
	Content sql.NullString `json:"content"`
}

func (q *Queries) UpdateNote(ctx context.Context, arg UpdateNoteParams) (Note, error) {
	row := q.db.QueryRowContext(ctx, updateNote, arg.ID, arg.Title, arg.Content)
	var i Note
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Content,
		&i.CreatedAt,
	)
	return i, err
}
